### ISSUE TITLE
Wrong site url in GitHub

### ISSUE THREAD

**Issue by aarongarciah** [modulz/stitches-site#13]
The current url in the repo about section points to https://stitches-site.modulz-deploys.com and should point to https://stitches.dev

<img width="282" alt="Screenshot 2020-09-02 at 20 54 04" src="https://user-images.githubusercontent.com/7225802/92024417-7abae980-ed5e-11ea-8e4a-8067cf716be0.png">

**Comment by peduarte** [comment]
Awesome, thanks!
