### ISSUE TITLE
"flash of light mode" issue

### ISSUE THREAD

**Issue by biowaffeln** [modulz/stitches-site#17]
When you set the site to dark mode, then reload it, you get the typical "flash of light mode" issue where the light theme flashes for half a second, then changes to dark theme.

I see that you're using the `noflash.js` script from `use-dark-mode` which should fix this issue, but for some reason it only works locally but not in production.

**Comment by peduarte** [comment]
haha yeah, Im not sure whats going on there 😂 

I haven't had a chance to investigate it further, but I'll make some time for that soon

(unless you beat me to it 😉 )

**Comment by biowaffeln** [comment]
I took a brief look at it in the morning, unfortunately I have no idea why it happens either 😅
Really annoying to debug as well, since it only appears in production builds. I might take a stab at it this weekend.

**Comment by biowaffeln** [comment]
Looks like it might be a bug with stitches. I think the problem lies somewhere here: https://github.com/modulz/stitches/blob/canary/packages/core/src/index.ts#L302

The style insertion is part of the `toString` method of the theme class. The problem is that this code gets called at different times in dev / prod builds, i.e. in production it only gets called _after_ the first render.

Perhaps one fix would be to generate the theme styles in [getStyles](https://github.com/modulz/stitches/blob/canary/packages/core/src/index.ts#L642) as well, so that it can be inserted in `_document`?

**Comment by peduarte** [comment]
Are you sure? 

We can validate it but I was pretty sure it was just an issue with reading the local storage and then setting the dark theme class in next. 

Right now I patched the issue by checking the mount state of the page. 

Bit hacky, but works quite well. You can see the changes in _app

**Comment by peduarte** [comment]
@biowaffeln its here btw https://github.com/modulz/stitches-site/commit/d0f7d6b1e2a715beb4452dbaf7dbcacbe3714a47

**Comment by biowaffeln** [comment]
Ah cool, nice to see you found a fix!

Yeah I thought so too, but when I debugged it I found that the dark theme class is actually applied correctly. Check it out here:
https://gofile.io/d/6u8j7G

**Comment by peduarte** [comment]
@biowaffeln  So the class is being added but at that point the CSS Variables for the theme hasn't been inserted?

**Comment by biowaffeln** [comment]
Yeah exactly! One solution would be for the CSS to be injected into a style tag in `_document` . Maybe as part of `getStyles`?
