### ISSUE TITLE
Trust and Safety issue.

### ISSUE THREAD

**Issue by imadatyatalah** [modulz/stitches-site#65]
I have tested [stitches website](https://stitches.dev/) via Lighthouse and I found that there is a Trust and Safety issue.
Solution: Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities. [Learn more](https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=lr).
I would like to work in this issue.

**Comment by peduarte** [comment]
Thanks, PRs welcome 😄
