### ISSUE TITLE
Button examples don't show up in light mode

### ISSUE THREAD

**Issue by raunaqgupta** [modulz/stitches-site#82]
## Light mode

<img width="1712" alt="CleanShot 2021-06-15 at 15 42 47@2x" src="https://user-images.githubusercontent.com/623670/122132787-5feaca80-cdf0-11eb-8303-12655075c34e.png">

## Dark mode

<img width="1712" alt="CleanShot 2021-06-15 at 15 43 14@2x" src="https://user-images.githubusercontent.com/623670/122132808-67aa6f00-cdf0-11eb-96dd-bc2c4a023403.png">

**Comment by peduarte** [comment]
Woooooah woah woah. 

Give me a minute.

**Comment by peduarte** [comment]
Fixed, thanks :D 

![CleanShot 2021-06-16 at 10 19 50@2x](https://user-images.githubusercontent.com/372831/122184321-662e8480-ce8c-11eb-8cdd-edc915120368.jpg)
