### ISSUE TITLE
The requested module is expected to be of type CommonJS

### ISSUE THREAD

**Issue by Deep-Codes** [modulz/stitches-site#89]
Hey!

not sure if I should ask this

I loved this documentation so was deep diving (mdx-bundler part) in the codebase

Doing `git clone + yarn + yarn dev`

Keep on getting this error

<img width="984" alt="Screenshot 2021-07-18 at 1 19 36 PM" src="https://user-images.githubusercontent.com/61158210/126059902-09e68e38-fb74-492c-8383-2695dfd9b44e.png">

Same error during `yarn build`

😅

**Comment by peduarte** [comment]
That's odd. Running locally here and building fine on Vercel. Maybe version of node?

**Comment by Deep-Codes** [comment]
> That's odd. Running locally here and building fine on Vercel. Maybe version of node?

yeah my bad 

```bash
nvm use <latest version>
```

should fix it :)
