### ISSUE TITLE
Clickable `<Card>`s should have `cursor: pointer`

### ISSUE THREAD

**Issue by jonahsnider** [modulz/stitches-site#92]
![`<Card>` elements on the home screen](https://user-images.githubusercontent.com/7608555/131382139-9a0f01cb-edb0-4c00-87bc-f24d17239803.png)

These are all clickable but don't have a matching cursor.

**Comment by peduarte** [comment]
Think it doesnt have it on purpose. @colmtuite ?

**Comment by colmtuite** [comment]
It's on purpose. It's a button, not a link.

**Comment by peduarte** [comment]
@jonahsnider thank you so much for the suggestion!
